apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustdesk-hbbr
  namespace: pmad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustdesk-hbbr
  template:
    metadata:
      labels:
        app: rustdesk-hbbr
    spec:
      containers:
      - name: rustdesk-hbbr
        image: rustdesk/rustdesk-server:latest
        command: ["hbbr"]
        args: ["-k", "_"]
        volumeMounts:
        - name: hbbr-data
          mountPath: /root
      volumes:
      - name: hbbr-data
        persistentVolumeClaim:
          claimName: rustdesk-pvc
