apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustdesk-hbbs
  namespace: pmad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustdesk-hbbs
  template:
    metadata:
      labels:
        app: rustdesk-hbbs
    spec:
      containers:
      - name: rustdesk-hbbs
        image: rustdesk/rustdesk-server:latest
        command: ["hbbs"]
        args: ["-r", "rustdesk-hbbr.pmad.svc.cluster.local:21117", "-k", "_"]
        volumeMounts:
        - name: hbbs-data
          mountPath: /root
      volumes:
      - name: hbbs-data
        persistentVolumeClaim:
          claimName: rustdesk-pvc
