apiVersion: v1
kind: PersistentVolume
metadata:
  name: rustdesk-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/rustdesk"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdesk-pvc
  namespace: pmad
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
