version: '3'

services:
  hbbs:
    container_name: pmad-hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r localhost:21117 -k _
    volumes:
      - ./hbbs:/root
    network_mode: "host"
    restart: always

  hbbr:
    container_name: pmad-hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr -k _
    volumes:
      - ./hbbr:/root
    network_mode: "host"
    restart: always
